export const cardData = [
  {
    id: 1,
    title: "Stock Broking",
    price: "₹ 1,00,000",
    term: "Annually per Exchange",
    feature1:
      "Annual fees for tracking complaince activities of each broking license.",
    feature2: "Manage daily, weekly, monthly reporting",
    feature3: "Task managment and project managment",
    feature4: "5 user including admin",
    feature5price: "₹750/-",
    feature5: "per user per month billed annually, (₹9000/- per Year)",
    feature6price: "₹1000/-",
    feature6: "per user per month billed monthly",
  },
  {
    id: 2,
    title: "Depository Participant",
    price: "₹ 1,00,000",
    term: "Annually per Depository Participant",
    feature1:
      "Annual fees for setting up compliance activities of each Depository license.",
    feature2: "Manage daily, weekly, monthly reporting",
    feature3: "Task managment and project managment",
    feature4: "5 user including admin",
    feature5price: "₹750/-",
    feature5: "per user per month billed annually, (₹9000/- per Year)",
    feature6price: "₹1000/-",
    feature6: "per user per month billed monthly",
  },
  {
    id: 3,
    title: "Portfolio Managers",
    price: "₹ 50,000",
    term: "Annually",
    feature1:
      "Annual fees for setting up compliance activities of PMS.",
    feature2: "Manage daily, weekly, monthly reporting",
    feature3: "Task managment and project managment",
    feature4: "3 user including admin",
    feature5price: "₹750/-",
    feature5: "per user per month billed annually, (₹9000/- per Year)",
    feature6price: "₹1000/-",
    feature6: "per user per month billed monthly",
  },
  {
    id: 4,
    title: "AIF",
    price: "₹ 50,000",
    term: "Annually",
    feature1:
      "Annual fees for setting up compliance activities of AIF.",
    feature2: "Manage daily, weekly, monthly reporting",
    feature3: "Task managment and project managment",
    feature4: "3 user including admin",
    feature5price: "₹750/-",
    feature5: "per user per month billed annually, (₹9000/- per Year)",
    feature6price: "₹1000/-",
    feature6: "per user per month billed monthly",
  },
  {
    id: 5,
    title: "Investment Advisors",
    price: "₹ 50,000",
    term: "Annually",
    feature1:
      "Annual fees for setting up compliance activities of RIA.",
    feature2: "Manage daily, weekly, monthly reporting",
    feature3: "Task managment and project managment",
    feature4: "3 user including admin",
    feature5price: "₹750/-",
    feature5: "per user per month billed annually, (₹9000/- per Year)",
    feature6price: "₹1000/-",
    feature6: "per user per month billed monthly",
  },
  {
    id: 6,
    title: "Research Analysts",
    price: "₹ 50,000",
    term: "Annually",
    feature1:
      "Annual fees for setting up compliance activities of RA.",
    feature2: "Manage daily, weekly, monthly reporting",
    feature3: "Task managment and project managment",
    feature4: "3 user including admin",
    feature5price: "₹750/-",
    feature5: "per user per month billed annually, (₹9000/- per Year)",
    feature6price: "₹1000/-",
    feature6: "per user per month billed monthly",
  },
];
