/* eslint-disable import/no-anonymous-default-export */
const OTHER_COMPLIANCE = "OTHER_COMPLIANCE/";

const UPDATE_SELECTED_LICENSES = OTHER_COMPLIANCE + "UPDATE_SELECTED_LICENSES";

const FETCH_LICENSES_REQUEST = OTHER_COMPLIANCE + "FETCH_LICENSES_REQUEST";
const FETCH_LICENSES_SUCCESS = OTHER_COMPLIANCE + "FETCH_LICENSES_SUCCESS";
const FETCH_LICENSES_FAILED = OTHER_COMPLIANCE + "FETCH_LICENSES_FAILED";

const FETCH_CHECKLIST_REQUEST = OTHER_COMPLIANCE + "FETCH_CHECKLIST_REQUEST";
const FETCH_CHECKLIST_SUCCESS = OTHER_COMPLIANCE + "FETCH_CHECKLIST_SUCCESS";
const FETCH_CHECKLIST_FAILED = OTHER_COMPLIANCE + "FETCH_CHECKLIST_FAILED";
const SET_CHECKLIST_DETAILS = OTHER_COMPLIANCE + "SET_CHECKLIST_DETAILS";
const FETCH_YOUR_COMPLIANCE_CHECKLIST_REQUEST =
  OTHER_COMPLIANCE + "FETCH_YOUR_COMPLIANCE_CHECKLIST_REQUEST";
const FETCH_YOUR_COMPLIANCE_CHECKLIST_SUCCESS =
  OTHER_COMPLIANCE + "FETCH_YOUR_COMPLIANCE_CHECKLIST_SUCCESS";
const FETCH_YOUR_COMPLIANCE_CHECKLIST_FAILED =
  OTHER_COMPLIANCE + "FETCH_YOUR_COMPLIANCE_CHECKLIST_FAILED";
const SET_YOUR_COMPLIANCE_CHECKLIST_DETAILS =
  OTHER_COMPLIANCE + "SET_YOUR_COMPLIANCE_CHECKLIST_DETAILS";

const CREATE_CUSTOM_CHECKLIST_REQUEST =
  OTHER_COMPLIANCE + "CREATE_CUSTOM_CHECKLIST_REQUEST";
const CREATE_CUSTOM_CHECKLIST_SUCCESS =
  OTHER_COMPLIANCE + "CREATE_CUSTOM_CHECKLIST_SUCCESS";
const CREATE_CUSTOM_CHECKLIST_FAILED =
  OTHER_COMPLIANCE + "CREATE_CUSTOM_CHECKLIST_FAILED";

export {
  FETCH_LICENSES_FAILED,
  FETCH_LICENSES_REQUEST,
  FETCH_LICENSES_SUCCESS,
  UPDATE_SELECTED_LICENSES,
  FETCH_CHECKLIST_FAILED,
  FETCH_CHECKLIST_REQUEST,
  FETCH_CHECKLIST_SUCCESS,
  CREATE_CUSTOM_CHECKLIST_FAILED,
  CREATE_CUSTOM_CHECKLIST_SUCCESS,
  CREATE_CUSTOM_CHECKLIST_REQUEST,
  FETCH_YOUR_COMPLIANCE_CHECKLIST_FAILED,
  FETCH_YOUR_COMPLIANCE_CHECKLIST_SUCCESS,
  FETCH_YOUR_COMPLIANCE_CHECKLIST_REQUEST,
  SET_YOUR_COMPLIANCE_CHECKLIST_DETAILS,
  SET_CHECKLIST_DETAILS,
};
