export const dashboardAuditInitialState = [
  {
    title: "company_name",
    dataField: "company_name",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "audit_category",
    dataField: "audit_category",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "assignment_name",
    dataField: "assignment_name",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "audit_template_name",
    dataField: "audit_template_name",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "start_date",
    dataField: "start_date",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "assigned_by",
    dataField: "assigned_by",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "question_count",
    dataField: "question_count",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
  {
    title: "checklist_count",
    dataField: "checklist_count",
    is_visible: true,
    filter_value: [],
    col: "columns[7].visible",
  },
];

export const dashboardAuditQuestionsInitialState = [
  {
    title: "company_name",
    dataField: "company_name",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "audit_category",
    dataField: "audit_category",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "assignment_name",
    dataField: "assignment_name",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "audit_template_name",
    dataField: "audit_template_name",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "start_date",
    dataField: "start_date",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "assigned_by",
    dataField: "assigned_by",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "question_count",
    dataField: "question_count",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
];

export const dashboardAuditChecklistInitialState = [
  {
    title: "company_name",
    dataField: "company_name",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "audit_category",
    dataField: "audit_category",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "assignment_name",
    dataField: "assignment_name",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "audit_template_name",
    dataField: "audit_template_name",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "start_date",
    dataField: "start_date",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "assigned_by",
    dataField: "assigned_by",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "checklist_count",
    dataField: "checklist_count",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
];

//dashboard question list view
export const dashboard_questions_initialState = [
  {
    title: "assignment_name",
    dataField: "assignment_name",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "questionnaire_section",
    dataField: "questionnaire_section",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "question",
    dataField: "question",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "reference_document",
    dataField: "reference_document",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "assigned_to_email",
    dataField: "assigned_to_email",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "attachment_type",
    dataField: "attachment_type",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "submitted_doc",
    dataField: "submitted_doc",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
  {
    title: "Add_Docs",
    dataField: "Add_Docs",
    is_visible: true,
    filter_value: [],
    col: "columns[7].visible",
  },
  {
    title: "mark_as_complete",
    dataField: "mark_as_complete",
    is_visible: true,
    filter_value: [],
    col: "columns[8].visible",
  },
  {
    title: "Answers",
    dataField: "Answers",
    is_visible: true,
    filter_value: [],
    col: "columns[9].visible",
  },
  {
    title: "Comments",
    dataField: "Comments",
    is_visible: true,
    filter_value: [],
    col: "columns[10].visible",
  },
  {
    title: "start_date",
    dataField: "start_date",
    is_visible: true,
    filter_value: [],
    col: "columns[11].visible",
  },
  {
    title: "to_be_completed",
    dataField: "to_be_completed",
    is_visible: true,
    filter_value: [],
    col: "columns[12].visible",
  },
];

//dashboard checklist list view
export const dashboard_checklist_initialState = [
  {
    title: "assignment_name",
    dataField: "assignment_name",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "checklist_section",
    dataField: "checklist_section",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "check_point",
    dataField: "check_point",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "assigned_to",
    dataField: "assigned_to",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "documents_relied_upon",
    dataField: "documents_relied_upon",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "attachment_format",
    dataField: "attachment_format",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "submitted_doc",
    dataField: "submitted_doc",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
  {
    title: "checkpoint_reference_list",
    dataField: "checkpoint_reference_list",
    is_visible: true,
    filter_value: [],
    col: "columns[7].visible",
  },
  {
    title: "submitted_doc_by_auditee",
    dataField: "submitted_doc_by_auditee",
    is_visible: true,
    filter_value: [],
    col: "columns[8].visible",
  },
  {
    title: "status",
    dataField: "status",
    is_visible: true,
    filter_value: [],
    col: "columns[9].visible",
  },
  {
    title: "severity",
    dataField: "severity",
    is_visible: true,
    filter_value: [],
    col: "columns[10].visible",
  },
  {
    title: "Add_Docs",
    dataField: "Add_Docs",
    is_visible: true,
    filter_value: [],
    col: "columns[11].visible",
  },
  {
    title: "Comments",
    dataField: "Comments",
    is_visible: true,
    filter_value: [],
    col: "columns[12].visible",
  },
  {
    title: "start_date",
    dataField: "start_date",
    is_visible: true,
    filter_value: [],
    col: "columns[13].visible",
  },
  {
    title: "to_be_completed",
    dataField: "to_be_completed",
    is_visible: true,
    filter_value: [],
    col: "columns[14].visible",
  },
  {
    title: "penalty",
    dataField: "penalty",
    is_visible: true,
    filter_value: [],
    col: "columns[15].visible",
  },
];

//custom template list view
export const template_List_View = [
  {
    title: "audit_template_name",
    dataField: "audit_template_name",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "audit_category",
    dataField: "audit_category",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "created_on",
    dataField: "created_on",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "total_question",
    dataField: "total_question",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "total_checklist",
    dataField: "total_checklist",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "edit",
    dataField: "edit",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "create_assignment",
    dataField: "create_assignment",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
];

//standard template list view
export const template_standard_List_View = [
  {
    title: "audit_template_name",
    dataField: "audit_template_name",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "audit_category",
    dataField: "audit_category",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "created_on",
    dataField: "created_on",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "total_question",
    dataField: "total_question",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "total_checklist",
    dataField: "total_checklist",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "assign",
    dataField: "assign",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "create",
    dataField: "create",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
];

//template question list view
export const template_List_View_Questions = [
  {
    title: "questionnaire_section",
    dataField: "questionnaire_section",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "question",
    dataField: "question",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "duration_of_completion",
    dataField: "duration_of_completion",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "attachment_type",
    dataField: "attachment_type",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
];

//template checklist list view
export const template_List_View_CheckList = [
  {
    title: "checklist_section",
    dataField: "checklist_section",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "check_point",
    dataField: "check_point",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "attachment_format",
    dataField: "attachment_format",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "duration_of_completion",
    dataField: "duration_of_completion",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "documents_relied_upon",
    dataField: "documents_relied_upon",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "severity",
    dataField: "severity",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "how_to_verify",
    dataField: "how_to_verify",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
  {
    title: "penalty",
    dataField: "penalty",
    is_visible: true,
    filter_value: [],
    col: "columns[7].visible",
  },
];

//assignment list view
export const assignment_List_View = [
  {
    title: "customer_name",
    dataField: "customer_name",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "audit_name",
    dataField: "audit_name",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "audit_template_name",
    dataField: "audit_template_name",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "start_date",
    dataField: "start_date",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "audit_category",
    dataField: "audit_category",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "questionnaire",
    dataField: "questionnaire",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "checkpoints",
    dataField: "checkpoints",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
  {
    title: "edit",
    dataField: "edit",
    is_visible: true,
    filter_value: [],
    col: "columns[7].visible",
  },
];

//assignment question list view
export const assignment_List_View_Questions = [
  {
    title: "questionnaire_section",
    dataField: "questionnaire_section",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "question",
    dataField: "question",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "start_date",
    dataField: "start_date",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "to_be_completed",
    dataField: "to_be_completed",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "assigned_to_email",
    dataField: "assigned_to_email",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "attachment_type",
    dataField: "attachment_type",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "submitted_doc",
    dataField: "submitted_doc",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
  {
    title: "reference_document",
    dataField: "reference_document",
    is_visible: true,
    filter_value: [],
    col: "columns[7].visible",
  },
  {
    title: "answers",
    dataField: "answers",
    is_visible: true,
    filter_value: [],
    col: "columns[8].visible",
  },
];

//assignment checklist list view column chooser
export const assignemnet_List_View_CheckList = [
  {
    title: "checklist_section",
    dataField: "checklist_section",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "check_point",
    dataField: "check_point",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "how_to_verify",
    dataField: "how_to_verify",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "start_date",
    dataField: "start_date",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "to_be_completed",
    dataField: "to_be_completed",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "assigned_by",
    dataField: "assigned_by",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "attachment_format",
    dataField: "attachment_format",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
  {
    title: "submitted_docs",
    dataField: "submitted_docs",
    is_visible: true,
    filter_value: [],
    col: "columns[7].visible",
  },
  {
    title: "checkpoint_reference_list",
    dataField: "checkpoint_reference_list",
    is_visible: true,
    filter_value: [],
    col: "columns[8].visible",
  },
  {
    title: "documents_relied_upon",
    dataField: "documents_relied_upon",
    is_visible: true,
    filter_value: [],
    col: "columns[9].visible",
  },
  {
    title: "severity",
    dataField: "severity",
    is_visible: true,
    filter_value: [],
    col: "columns[10].visible",
  },
  {
    title: "penalty",
    dataField: "penalty",
    is_visible: true,
    filter_value: [],
    col: "columns[11].visible",
  },
  {
    title: "status",
    dataField: "status",
    is_visible: true,
    filter_value: [],
    col: "columns[12].visible",
  },
];

//company column chooser list view
export const company_list_view = [
  {
    title: "company_name",
    dataField: "company_name",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "register_id",
    dataField: "register_id",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "company_type",
    dataField: "company_type",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "phone_no",
    dataField: "phone_no",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },
  {
    title: "email_id",
    dataField: "email_id",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "branch_count",
    dataField: "branch_count",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
  {
    title: "edit",
    dataField: "edit",
    is_visible: true,
    filter_value: [],
    col: "columns[6].visible",
  },
  {
    title: "delete",
    dataField: "delete",
    is_visible: true,
    filter_value: [],
    col: "columns[7].visible",
  },
];

//brnach column chooser
export const branch_list_view = [
  {
    title: "branch_location",
    dataField: "branch_location",
    is_visible: true,
    filter_value: [],
    col: "columns[0].visible",
    disabled: true,
  },
  {
    title: "manager_name",
    dataField: "manager_name",
    is_visible: true,
    filter_value: [],
    col: "columns[1].visible",
  },
  {
    title: "manager_phone_no",
    dataField: "manager_phone_no",
    is_visible: true,
    filter_value: [],
    col: "columns[2].visible",
  },
  {
    title: "manager_emailid",
    dataField: "manager_emailid",
    is_visible: true,
    filter_value: [],
    col: "columns[3].visible",
  },

  {
    title: "edit",
    dataField: "edit",
    is_visible: true,
    filter_value: [],
    col: "columns[4].visible",
  },
  {
    title: "delete",
    dataField: "delete",
    is_visible: true,
    filter_value: [],
    col: "columns[5].visible",
  },
];
