export const ADD_NEW_SECTION = "ADD_NEW_SECTION";
export const SET_SECTION_NAME = "SET_SECTION_NAME";
export const GET_SECTION_NAME = "GET_SECTION_NAME";

export const SET_TEMPLATE_ID = "SET_TEMPLATE_ID";
export const GET_TEMPLATE_ID = "GET_TEMPLATE_ID";

export const SET_QUESTION_LIST = "SET_QUESTION_LIST";
export const GET_QUESTION_LIST = "GET_QUESTION_LIST";

export const SET_AUDIT_ASSIGNMENT_BASIC_DETAILS =
  "SET_AUDIT_ASSIGNMENT_BASIC_DETAILS";
export const GET_AUDIT_ASSIGNMENT_BASIC_DETAILS =
  "GET_AUDIT_ASSIGNMENT_BASIC_DETAILS";

export const SET_ASSIGNMENT_ID = "SET_ASSIGNMENT_ID";

export const SET_AUDIT_ADDRESS_DETAILS = "SET_AUDIT_ADDRESS_DETAILS";
export const GET_AUDIT_ADDRESS_DETAILS = "GET_AUDIT_ADDRESS_DETAILS";
export const SET_AUDIT_QUASTIONARIE_DETAILS = "SET_AUDIT_QUASTIONARIE_DETAILS";

export const SET_COMPANY_DATA = "SET_COMPANY_DATA";
export const SET_BRANCH_DATA = "SET_BRANCH_DATA";

export const SET_DELETE_COMPANY = "SET_DELETE_COMPANY";
export const SET_DELETE_BRANCH = "SET_DELETE_BRANCH";

export const SET_EDIT_STATE = "SET_EDIT_STATE";

export const SET_ASSIGNMENT_DETAIL = "SET_ASSIGNMENT_DETAIL";

export const ASSIGNMENT_GET_ASSIGNMENT_LIST = "ASSIGNMENT_GET_ASSIGNMENT_LIST";
export const ASSIGNMENT_GET_ASSIGNMENT_QUESTIONNARIE =
  "ASSIGNMENT_GET_ASSIGNMENT_QUESTIONNARIE";
export const ASSIGNMENT_GET_ASSIGNMENT_CHECKPOINTS =
  "ASSIGNMENT_GET_ASSIGNMENT_CHECKPOINTS";
export const ASSIGNMENT_SET_ASSIGNMENT_LIST = "ASSIGNMENT_SET_ASSIGNMENT_LIST";
export const ASSIGNMENT_SET_ASSIGNMENT_QUESTIONNARIE =
  "ASSIGNMENT_SET_ASSIGNMENT_QUESTIONNARIE";
export const ASSIGNMENT_SET_ASSIGNMENT_CHECKPOINTS =
  "ASSIGNMENT_SET_ASSIGNMENT_CHECKPOINTS";

export const MARK_AS_COMPLETE_MODAL_ISOPEN = "MARK_AS_COMPLETE_MODAL_ISOPEN";
export const MARK_AS_COMPLETE_MODAL_ISCLOSE = "MARK_AS_COMPLETE_MODAL_ISCLOSE";
export const MARK_AS_COMPLETE_SET_DATA = "MARK_AS_COMPLETE_SET_DATA";

export const CURRENT_OPENED_ASSIGNMENT_NAME = "CURRENT_OPENED_ASSIGNMENT_NAME";

export const CLEAR_ASSIGNMNET_DETAIL = "CLEAR_ASSIGNMNET_DETAIL";
export const CLEAR_ASSIGNMENT_ID ="CLEAR_ASSIGNMENT_ID";

export const SET_LONG_TEXT_POPUP = "SET_LONG_TEXT_POPUP";